config/routes.rb
Rails.application.routes.draw do 

  namespace :admin do
    resources :users
    resources :administrateurs
    resources :enseignants
    resources :etudiants
    resources :matieres
    resources :epreuves
    resources :notes

    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :notes

  resources :matieres

  resources :epreuves

  namespace :validation do
    resources :users
  end
  
  root 'home#index'

  post 'matieres/newmatels' => 'matieres#newmatels', as: :newmatels

  get 'javascripts/dynamic_epreuves.:format' => 'javascripts#dynamic_epreuves'

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :user
end

app/controllers/admin/notes_controller.rb
module Admin
  class NotesController < Admin::ApplicationController
    load_and_authorize_resource
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Enseignant.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Enseignant.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
	load_and_authorize_resource

	def new
        if current_user.kind_of? Enseignant
          if not(params[:epreuve_id] == nil)
              @epreuve = params[:epreuve_id]
              @matiere_id = Epreuve.find(@epreuve).matiere_id
              @eleves = Matiere.find(@matiere_id).users
              @nb_eleves = @eleves.count
              @notestab = []
              @nb_eleves.times do
                  @notestab << Note.new
              end
          else
            flash[:alert] = 'Aucune épreuve sélectionnée'
            redirect_to root_path
          end
        else 
          flash[:alert] = 'Accès refusé !'
          redirect_to root_path
        end
    end

    def create
        if params.has_key?("note")
          @note = Note.create(params["note"].permit(:user_id, :matiere_id, :epreuve_id, :note))
          if (Note.where(user_id: @note.user_id).where(epreuve_id: @note.epreuve_id).count > 1)
            @epreuve_id = @note.epreuve_id
            @note.destroy
            flash[:alert] = 'Note déjà existante'
            redirect_to new_note_path({ :epreuve_id => @epreuve.id })
          else
            flash[:notice] = 'Note ajoutée avec succès'
            redirect_to epreuves_path
          end
        else
          @flag=true
          params["notes"].each do |note|
            if note["note"] != "" 
              @note = Note.create(note.permit(:user_id, :matiere_id, :epreuve_id, :note))
              if (Note.where(user_id: @note.user_id).where(epreuve_id: @note.epreuve_id).count > 1)
                @note.destroy
                @flag=false
              end
            end
          end
          if @flag == false
            flash[:alert] = 'Une note éxistait déjà !'
            redirect_to root_path
          else
            flash[:notice] = 'Notes ajoutées avec succès'
            redirect_to epreuves_path
          end
        end
    end

	def index
        if current_user.kind_of? Etudiant
          @note_list = Note.where(user_id: current_user.id)
        else 
          @matiere_list = Matiere.where(user_id: current_user.id)

          @note_list = []
          @matiere_list.each do |matiere|
            epreuves = Epreuve.where(matiere_id: matiere.id)
            epreuves.each do |epreuve|
              @note_list << Note.where(epreuve_id: epreuve.id)
            end
          end
        end
	end

	 def edit
        @note = Note.find(params[:id])
    end

    def update
        @note = Note.find(params[:id])
        if @note.update_attributes(params["note"].permit(:user_id, :matiere_id, :epreuve_id, :note))
            flash[:notice] = 'Modification de la note effectuée avec succès'
            redirect_to notes_path
        else
            render :action => 'edit'
        end
    end

	private
end

app/views/notes/edit.html.erb
<%= javascript 'dynamic_epreuves' %>
<div class="space_top">
	<h2>Modification de la note</h2>

	<%= form_for @note do |f| %>
	<div class="field is-4 column is-centered space_top-small2">
		<span class="select">
		 <%= f.collection_select :user_id, User.where(type:'Etudiant'), :id, :prenom_et_nom, include_blank: 'Sélectionnez un étudiant', class: "select" %>
		</span>
	</div>
	<div class="field is-4 column is-centered ">
		 <span class="select">
		 <%= f.collection_select :matiere_id, Matiere.where(user_id: current_user.id), :id, :titre, include_blank: 'Sélectionnez une matière', class: "select" %>
		 </span>
	</div>
	<div class="field is-4 column is-centered">
		 <span class="select">
		 <p id="epreuve_field">
		 <%= f.collection_select :epreuve_id, Epreuve.all ,:id, :titre, include_blank: 'Sélectionnez une épreuve' %>
		 </p>
		 </span>
	</div>
	<div class="field is-1 column is-centered">
		<%= f.text_field :note, placeholder: "Note", class: "input"%>
	</div>
	<div class="actions columns is-centered space_top-small2">
		<%= f.submit "Enregistrer", class: "button is-warning is-medium" %>
	</div>
	<% end %>
	<div class="corner_left">
		<%= link_to "Retour", :back, :class => 'button is-dark' %>
	</div>
</div>

app/views/notes/index.html.erb
<div class="space_top-small">
	<h2> Mes notes </h2>
	<%if @note_list.empty? %>
		Aucune note
		<div class="corner_left">
			<%= link_to "Accueil", root_path, :class => 'button is-dark' %>
		</div>

	<%else%>

		<% if current_user.kind_of? Etudiant %>
			<div class="columns space_top-small">
				<div class="column is-9 is-centered">
					<table  class="table overflow-y">
						<thead>
							<th>Matiere</th>
							<th>Epreuve</th>
							<th>Note</th>
						</thead>
						<tbody>	
							<% for @note in @note_list %>
							<tr>
							    <td> <%= Matiere.find(@note.matiere_id).titre %> </td>
							    <td> <%= Epreuve.find(@note.epreuve_id).titre %> </td>
							    <td> <%= @note.note %> </td>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
			</div>
			<div class="corner_left">
	  			<%= link_to "Accueil", root_path, :class => 'button is-dark' %>
			</div>

		<% else %>
			<div class="scrollable" id="scrollable">
				
				<% for @epreuve in @note_list %>
					<%if not(@epreuve.empty?) %>
						<div class="entete ">
							<%= Matiere.find(@epreuve[0].matiere_id).titre %>
							-<%= Epreuve.find(@epreuve[0].epreuve_id).titre %>
						</div>
						<div class="columns">
							<div class="column is-9 is-centered">
								<table  class="table">
									<thead>
										<th>Nom</th>
										<th>Prénom</th>
										<th>Note</th>
										<th>Modifier</th>
									</thead>
									<tbody>	
										<% for @note in @epreuve %>
										<tr>
											<% @user = User.find(@note.user_id) %>
										    <td> <%= @user.nom %> </td>
										    <td> <%= @user.prenom %> </td>
										    <td> <%= @note.note %> </td>
										    <td><%= link_to raw("<span class=\"icon\"><i class=\"fa fa-pencil-square\" aria-hidden=\"true\"></i></span><span>Modifier cette note</span>"), edit_note_path(@note), class: "button" %></td>
										</tr>
										<% end %>
									</tbody>
								</table>
							</div>
						</div>
					<% end %>
				<% end %>

			</div>
		<div class="corner_left">
			<%= link_to "Accueil", root_path, :class => 'button is-dark' %>
		</div>
		<% end %>


	<% end %>
</div>

app/views/notes/new.html.erb
<% if not(params[:epreuve_id] == nil) %>

<%= javascript 'dynamic_epreuves' %>
<div class="space_top">
<h2>Nouvelle note</h2>

<% @i=0 %>
<%= form_tag notes_path do %>
<div class="scrollable" id="scrollable">
  <% @notestab.each do |note| %>
    <%= fields_for 'notes[]', note do |f| %>

    <%= f.text_field :user_id, :value => @eleves[@i].id, class: "hidden" %>
  	<%= f.text_field :matiere_id, :value => @matiere_id, class: "hidden"  %>
  	<%= f.text_field :epreuve_id, :value => @epreuve, class: "hidden"  %>
    <div class="columns is-centered">
    <div class="field column better_lineheight isnot-flex">
    	<%= @eleves[@i].nom %>
    	<%= @eleves[@i].prenom %>
    </div>
    <div class="field is-2 column">
    <%= f.number_field :note, :min => 0, :max => 20 , :step => 0.5, placeholder: "Note", class: "input"%>
    </div>
    </div>
    <% @i+=1 %> 
    <% end %>
  <% end %>
</div>
  <div class="actions columns is-centered space_top-small">
     <%= submit_tag "Enregistrer", class: "button is-warning is-medium" %>
  </div>
<% end %>

  <div class="corner_left">
    <%= link_to "Retour", :back, :class => 'button is-dark' %>
  </div>
</div>

<% end %>

app/views/notes/new_single.html.erb
<%= javascript 'dynamic_epreuves' %>

<h2>Nouvelle note</h2>

<%= form_for @note do |f| %>
 <%= f.collection_select :user_id, User.where(type:'Etudiant'), :id, :prenom_et_nom, include_blank: 'Sélectionnez un étudiant' %>
 <label for="note_matiere_id">Matière:</label>
 <%= f.collection_select :matiere_id, Matiere.where(user_id: current_user.id), :id, :titre, include_blank: 'Sélectionnez une matière' %>
 <p id="epreuve_field">
 <label for="note_epreuve_id">Epreuve:</label>
 <%= f.collection_select :epreuve_id, Epreuve.all ,:id, :titre, include_blank: 'Sélectionnez une épreuve' %>
 </p>

<%= f.text_field :note, placeholder: "Note"%>
<%= f.submit "Enregistrer"%>
<% end %>
<%= link_to "Retour", :back%>