config/routes.rb
Rails.application.routes.draw do 

  namespace :admin do
    resources :users
    resources :administrateurs
    resources :enseignants
    resources :etudiants
    resources :matieres
    resources :epreuves
    resources :notes

    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :notes

  resources :matieres

  resources :epreuves

  namespace :validation do
    resources :users
  end
  
  root 'home#index'

  post 'matieres/newmatels' => 'matieres#newmatels', as: :newmatels

  get 'javascripts/dynamic_epreuves.:format' => 'javascripts#dynamic_epreuves'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    before_action :authenticate_user!
    load_and_authorize_resource :only => [:home]
	
	def index
		if current_user.kind_of? Etudiant
           	@type = Etudiant
        else if current_user.kind_of? Enseignant
            @type = Enseignant
        else 
        	@type = Administrateur
        end
    	end
	end
end

app/views/home/index.html.erb
<html>
  <head>
  </head>
  <body>
	<%= render "layouts/_navigation_links" %>
    <!-- Affichage des liens de navigation!-->
	<!--Fin Affichage des liens de navigation!-->

	  	<% if current_user.kind_of? Administrateur %>
	  		<div class="columns space_top">
				<div class="field is-4 column is-centered is-half-mobile is-one-third-tablet is-one-quarter-desktop">
					<%= link_to "Administrer",  admin_root_path, class: "button is-warning is-medium" %>
				</div>
				<div class="field is-4 column is-centered is-half-mobile is-one-third-tablet is-one-quarter-desktop">
					<%= link_to "Valider un enseignant",  validation_users_path, class: "button is-warning is-medium" %>
				</div>
			</div>

		<% end %>
 
		<% if current_user.kind_of? Etudiant %>
		<div class="columns space_top ">
				<div class="field is-4 column is-centered is-half-mobile is-one-third-tablet is-one-quarter-desktop">
					<%= link_to "Consulter mes notes",  notes_path, class: "button is-warning is-medium" %>
				</div>
				<div class="field is-4 column is-centered is-half-mobile is-one-third-tablet is-one-quarter-desktop">
					<%= link_to "Consulter mes épreuves",  epreuves_path, class: "button is-warning is-medium" %>
				</div>
		</div>
		<% end %>
	

  	
		<% if current_user.kind_of? Enseignant %>		
			<div class="columns space_top-small2">
					<div class="field column is-4 is-centered is-half-mobile is-one-third-tablet is-one-quarter-desktop">
						<%= link_to "Inscrire un étudiant",  new_validation_user_path, class: "button is-warning" %>
					</div>
					<div class="field column is-4 is-centered is-half-mobile is-one-third-tablet is-one-quarter-desktop">
						<%= link_to "Liste des étudiants",  validation_users_path, class: "button is-warning" %>
					</div>
			</div>
			<div class="columns space_top-small2">
				<div class="field is-4 column is-centered is-half-mobile is-one-third-tablet is-one-quarter-desktop">
				<%= link_to "Ajouter une épreuve",  new_epreuve_path, class: "button is-warning" %>
				</div>
				<div class="field is-4 column is-centered is-half-mobile is-one-third-tablet is-one-quarter-desktop">
				<%= link_to "Ajouter une matière",  new_matiere_path, class: "button is-warning" %>
				</div>
			</div>
			<div class="columns space_top-small2">
				<div class="field is-4 column is-offset-1 is-half-mobile is-one-third-tablet is-one-quarter-desktop">
					<%= link_to "Mes épreuves / ajouter les notes d'une épreuve",  epreuves_path, class: "button is-warning" %>
				</div>
				<div class="field column is-4 is-offset-3 is-8-mobile is-one-third-tablet is-one-quarter-desktop">
					<%= link_to "Mes matières / ajouter des étudiants à une matière",  matieres_path, class: "button is-warning " %>
				</div>
			</div>
			<div class="columns space_top-small2">
				<div class="field is-4 column is-centered is-11-mobile is-one-third-tablet">
					<%= link_to "Modifier une note / mes notes enregistrées",  notes_path, class: "button is-warning" %>
				</div>
			</div>
		<% end %>


  </body>
</html>