config/routes.rb
Rails.application.routes.draw do 

  namespace :admin do
    resources :users
    resources :administrateurs
    resources :enseignants
    resources :etudiants
    resources :matieres
    resources :epreuves
    resources :notes

    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :notes

  resources :matieres

  resources :epreuves

  namespace :validation do
    resources :users
  end
  
  root 'home#index'

  post 'matieres/newmatels' => 'matieres#newmatels', as: :newmatels

  get 'javascripts/dynamic_epreuves.:format' => 'javascripts#dynamic_epreuves'

end

app/models/epreuve.rb
class Epreuve < ActiveRecord::Base
end

app/controllers/admin/epreuves_controller.rb
module Admin
  class EpreuvesController < Admin::ApplicationController
    load_and_authorize_resource
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Enseignant.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Enseignant.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/epreuves_controller.rb
class EpreuvesController < ApplicationController
    before_action :authenticate_user!
    load_and_authorize_resource
    
	def new
		@epreuve = Epreuve.new
	end

	def create
        @epreuve = Epreuve.new(epreuve_params)
        if @epreuve.save
            flash[:notice] = "Epreuve #{@epreuve.titre} ajoutée avec succès"
            redirect_to epreuves_path
        else
            render :action => 'new'
        end
    end

    def index
        if current_user.kind_of? Etudiant
            @epreuve_list =[]
            @matieres=current_user.matieres
            @matieres.each do |matiere|
                @i = 0
                tmp = Epreuve.where(matiere_id: matiere.id)
                while not(tmp[@i] == nil) do
                    @epreuve_list.push(tmp[@i])
                    @i = @i+1
                end
            end
        else 
            @matieres = Matiere.where(user_id: current_user.id)
            @epreuve_list =[]
            @matieres.each do |matiere|
               @i = 0
               tmp = Epreuve.where(matiere_id: matiere.id)
               while not(tmp[@i] == nil) do
                    @epreuve_list.push(tmp[@i])
                    @i = @i+1
               end
            end
        end
            
    end


    private

    def epreuve_params
        params.require(:epreuve).permit(:titre, :date, :matiere_id)
    end
end

app/helpers/epreuves_helper.rb
module EpreuvesHelper
end

app/views/epreuves/index.html.erb
<div class="space_top-small">
	<h2> Mes épreuves </h2>
	
<%if @epreuve_list.empty? %>
	Aucune épreuve
	<div class="corner_left">
		<%= link_to "Accueil", root_path, :class => 'button is-dark' %>
	</div>
	<% if current_user.kind_of? Enseignant %>
		   <%= link_to "Ajouter une épreuve",  new_epreuve_path, class: "button is-success corner_right" %>
	<% end %>

<%else%>
	<div class="columns space_top-small2">
		<div class="column is-9 is-centered">
			<table class="overflow-y">
				<thead>
					<th>Epreuve</th>
					<th>Matiere</th>
					<th>Date</th>
					<% if current_user.kind_of? Enseignant %>
				    	<th>Ajouter une note</th>
				    <% end %>
				</thead>
				<tbody>
					<% for @epreuve in @epreuve_list %>	
					<tr>
						<td><%= @epreuve.titre %></td>
						<td><%= Matiere.find(@epreuve.matiere_id).titre %></td>
						<td><%= @epreuve.date %></td>

					    <% if current_user.kind_of? Enseignant %>
					    <td>
					    	<%= link_to raw("<span class=\"icon\"><i class=\"fa fa-plus\" aria-hidden=\"true\"></i></span><span>Ajouter une note</span>"),  new_note_path({ :epreuve_id => @epreuve.id }), class: "button" %>
					    </td>
					    <% end %>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>

	
	<div class="corner_left">
		<%= link_to "Accueil", root_path, :class => 'button is-dark' %>
	</div>
	<% if current_user.kind_of? Enseignant %>
		   <%= link_to "Ajouter une épreuve",  new_epreuve_path, class: "button is-success corner_right" %>
	<% end %>
</div>
<%end%>

app/views/epreuves/new.html.erb
<div class="space_top">
	<h2>Nouvelle épreuve</h2>

<%= form_for @epreuve do |f| %>
	<div class="field is-4 column is-centered space_top-small2">
		<span class="select">
			<%= f.collection_select :matiere_id, Matiere.where(user_id: current_user.id) , :id, :titre, include_blank: 'Sélectionnez une matière', class: "select" %>
		</span>
	</div>

	<div class="field is-2 column is-centered">
		<%= f.label :Date_epreuve, "Date de l'épreuve" %>
		<%= f.date_field :date, class: "input"  %>
	</div>

	<div class="field is-3 column is-centered">
		<%= f.text_field :titre, placeholder: "Epreuve", class: "input" %>
	</div>

	<div class="actions columns is-centered space_top-small2">
		<%= f.submit "Enregistrer", class: "button is-warning is-medium" %>
	</div>

<% end %>
	<div class="corner_left">
		<%= link_to "Accueil", root_path, :class => 'button is-dark' %>
	</div>
</div>