config/routes.rb
Rails.application.routes.draw do 

  namespace :admin do
    resources :users
    resources :administrateurs
    resources :enseignants
    resources :etudiants
    resources :matieres
    resources :epreuves
    resources :notes

    root to: "users#index"
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :notes

  resources :matieres

  resources :epreuves

  namespace :validation do
    resources :users
  end
  
  root 'home#index'

  post 'matieres/newmatels' => 'matieres#newmatels', as: :newmatels

  get 'javascripts/dynamic_epreuves.:format' => 'javascripts#dynamic_epreuves'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users_matieres
  has_many :matieres, through: :users_matieres

  has_many :notes
  accepts_nested_attributes_for :notes, :reject_if => lambda { |b| b[:note].blank? }

	def prenom_et_nom
	  "#{nom} #{prenom}"
	end

	def active_for_authentication? 
    	super && approved? 
  	end 

  	def inactive_message 
    	if !approved? 
      		:not_approved 
   		else 
      		super # Use whatever other message 
    	end 
  	end

     def self.send_reset_password_instructions(attributes={})
      recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
      if !recoverable.approved?
        recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
      elsif recoverable.persisted?
        recoverable.send_reset_password_instructions
      end
      recoverable
    end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    load_and_authorize_resource
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 #before_action :sign_up_params, only: [:create]
 #before_action :configure_account_update_params, only: [:update]

def create
    build_resource(registration_params)

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        respond_with resource, :location => after_sign_up_path_for(resource)
      end
    else
      clean_up_passwords
      respond_with resource
    end
  end  

  private

  def registration_params
    params.require(:user).permit(:email, :nom, :prenom, :type, :password, :password_confirmation)
  end


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  #def account_update_params
    #params.require(:user).permit(:prenom, :nom, :email, :password, :password_confirmation, :type)
  #end
  
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/validation/users_controller.rb
class Validation::UsersController < ApplicationController
    before_action :authenticate_user!
    before_filter :verify_user
   
	def index
        if params[:approved] == "false"
          @users = User.where(approved: false)
          @enseignants = User.where(type: Enseignant).where(approved: false)
        else
          @users = User.all
          @enseignants = User.where(type: Enseignant)
        end
        @etudiants = User.where(type: Etudiant)
    end

    def edit
        @user = User.find(params[:id]).becomes(User)
    end

    def update
        @user = User.find(params[:id])
        if @user.update_attributes(user_params)
            flash[:notice] = 'Mise à jour de l\' enseignant effectuée avec succès'
            redirect_to validation_users_path
        else
            @user=@user.becomes(User)
            render :action => 'edit'
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        @user.password= Devise.friendly_token.first(8)
        if @user.save
            flash[:notice] = 'Etudiant ajouté avec succès'
            # Tell the UserMailer to send a welcome email after save
            UserMailer.invitation_email(@user).deliver_now
            redirect_to validation_users_path
        end
    end

	private

    def user_params
        params.require(:user).permit(:nom, :prenom, :email, :type, :password, :approved)
    end

    def verify_user
        if current_user.kind_of? Etudiant
            redirect_to root_url
            flash[:alert] = "Accès refusé !"
        end
    end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/validation/users/edit.html.erb
<div class="space_top">
    <% if current_user.kind_of? Administrateur %>
        <h2>Valider l'enseignant</h2>

        <%= form_for [:validation, @user] do |f| %>
            <div class="field is-2 column is-centered">
                <%= f.text_field :nom, class: "input" %>
            </div>
            <div class="field is-2 column is-centered">
                <%= f.text_field :prenom, class: "input" %>
            </div>
            <div class="field is-3 column is-centered">
                <%= f.email_field :email, class: "input" %>
            </div>
            <div class="field is-2 column is-centered">
                <%= f.label :approved, "Validé?"%>
                <%= f.check_box :approved%>
            </div>
            <div class="actions columns is-centered space_top-small2">
                <%= f.submit "Enregistrer", class: "button is-warning"%>
            </div>
        <% end %>
        <div class="corner_left">
            <%= link_to "Retour", :back, :class => 'button is-dark' %>
        </div>
    <% end %>

</div>

app/views/validation/users/index.html.erb
<div class="space_top-small">
	<% if current_user.kind_of? Administrateur %>
		<h2>Validation des enseignants</h2>
		<div class="column is-9 is-centered interligne">
		<%= link_to "Tous les enseignants", :action => "index" %>
		</div>
		<div class="column is-9 is-centered interligne">
			<%= link_to "Enseignants en attente de validation", :action => "index", :approved => "false" %>
		</div>
			<div class="column is-9 is-centered">
				<table  class="table overflow-y">
					<thead>
						<th>Nom</th>
						<th>Prénom</th>
						<th>Email</th>
						<th>Validation</th>
						<th>Valider</th>
						<th>Type</th>
					</thead>
					<tbody>
						<% for @user in @enseignants %>
					    <tr>
					      <td><%= @user.nom %></td>
					      <td><%= @user.prenom %></td>
					      <td><%= @user.email %></td>
					      <td><%= @user.type %></td>
					      <td><%= @user.approved %></td>
					      <td>
					    	<%= link_to raw("<span class=\"icon\"><i class=\"fa fa-check\" aria-hidden=\"true\"></i></span><span>Valider cet utilisateur</span>"),  edit_validation_user_path(@user), class: "button" %>
					      </td>
					    </tr>
						<% end %>
					</tbody>
				</table>
			</div>
</div>
	
	<% else %>
<div class="space_top-small">
		<h2>Liste des étudiants</h2>
		<div class="column is-9 is-centered">
			<table  class="table overflow-y">
				<thead>
					<th>Nom</th>
					<th>Prénom</th>
					<th>Email</th>
				</thead>
	 			<tbody>
					<% for @user in @etudiants %>
				    <tr>
				      <td><%= @user.nom %></td>
				      <td><%= @user.prenom %></td>
				      <td><%= @user.email %></td>
				    </tr>
		 			<% end %>
		 		</tbody>
		 	</table>
		<%= link_to "Ajouter un étudiant", new_validation_user_path, class: "button is-success corner_right" %>
	</div>
</div>
	<% end %>

	<div class="corner_left">
		<%= link_to "Accueil", root_path, :class => 'button is-dark' %>
	</div>

app/views/validation/users/new.html.erb
<div class="space_top">
<h2>Inscrire un élève</h2>

    <%= form_for [:validation, @user] do |f| %>
        <div class="field is-3 column is-centered">
            <%= f.text_field :nom, placeholder: "Nom", class: "input" %>
        </div>
        <div class="field is-3 column is-centered">
            <%= f.text_field :prenom, placeholder: "Prénom", class: "input" %>
        </div>
        <div class="field is-3 column is-centered">
            <%= f.email_field :email, placeholder: "Email", class: "input" %>
        </div>
        <div class="field is-4 column is-centered">
            <%= f.label :approved, "Validé ?"%>
            <%= f.check_box :approved, class:"checkbox" %>
        </div>
       
        <div class="field">
            <%= f.radio_button :type, "Etudiant", :checked => true, class: "hidden" %>
            <%= f.label :type, "Etudiant", class: "hidden" %>
        </div>

        <div class="actions columns is-centered space_top-small">
            <%= f.submit "Enregistrer", class: "button is-warning" %>
        </div>
    <% end %>

    <div class="corner_left">
      <%= link_to "Retour", :back, :class => 'button is-dark' %>
    </div>

</div>